
package br.com.aevee.port_finan.fornecedores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_Fornecedores_req", targetNamespace = "http://www.aevee.com.br/port_finan/fornecedores")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.fornecedores.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SIFornecedoresReq {


    /**
     * 
     * @param mtListarFornecedoresReq
     * @return
     *     returns br.com.aevee.port_finan.fornecedores.DTListarFornecedoresOUT
     */
    @WebMethod(operationName = "Listar", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Listar_Fornecedores_resp", targetNamespace = "", partName = "MT_Listar_Fornecedores_resp")
    public DTListarFornecedoresOUT listar(
        @WebParam(name = "MT_Listar_Fornecedores_req", targetNamespace = "", partName = "MT_Listar_Fornecedores_req")
        DTListarFornecedoresINB mtListarFornecedoresReq);

}
