
package br.com.aevee.port_finan.fornecedores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Fornecedores_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/fornecedores", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/fornecedor.wsdl")
public class SIFornecedoresReqService
    extends Service
{

    private final static URL SIFORNECEDORESREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIFORNECEDORESREQSERVICE_EXCEPTION;
    private final static QName SIFORNECEDORESREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/fornecedores", "SI_Fornecedores_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/fornecedor.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("fornecedor.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIFORNECEDORESREQSERVICE_WSDL_LOCATION = url;
        SIFORNECEDORESREQSERVICE_EXCEPTION = e;
    }

    public SIFornecedoresReqService() {
        super(__getWsdlLocation(), SIFORNECEDORESREQSERVICE_QNAME);
    }

    public SIFornecedoresReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIFORNECEDORESREQSERVICE_QNAME, features);
    }

    public SIFornecedoresReqService(URL wsdlLocation) {
        super(wsdlLocation, SIFORNECEDORESREQSERVICE_QNAME);
    }

    public SIFornecedoresReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIFORNECEDORESREQSERVICE_QNAME, features);
    }

    public SIFornecedoresReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIFornecedoresReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIFornecedoresReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIFornecedoresReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/fornecedores", "HTTP_Port"), SIFornecedoresReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIFornecedoresReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIFornecedoresReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/fornecedores", "HTTP_Port"), SIFornecedoresReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIFornecedoresReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIFornecedoresReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/fornecedores", "HTTPS_Port"), SIFornecedoresReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIFornecedoresReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIFornecedoresReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/fornecedores", "HTTPS_Port"), SIFornecedoresReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIFORNECEDORESREQSERVICE_EXCEPTION!= null) {
            throw SIFORNECEDORESREQSERVICE_EXCEPTION;
        }
        return SIFORNECEDORESREQSERVICE_WSDL_LOCATION;
    }

}
