
package br.com.aevee.port_finan.usuario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_User_Aceite_Contrato_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/usuario", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/aceiteContrato.wsdl")
public class SIUserAceiteContratoReqService
    extends Service
{

    private final static URL SIUSERACEITECONTRATOREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIUSERACEITECONTRATOREQSERVICE_EXCEPTION;
    private final static QName SIUSERACEITECONTRATOREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/usuario", "SI_User_Aceite_Contrato_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/aceiteContrato.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("aceiteContrato.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIUSERACEITECONTRATOREQSERVICE_WSDL_LOCATION = url;
        SIUSERACEITECONTRATOREQSERVICE_EXCEPTION = e;
    }

    public SIUserAceiteContratoReqService() {
        super(__getWsdlLocation(), SIUSERACEITECONTRATOREQSERVICE_QNAME);
    }

    public SIUserAceiteContratoReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIUSERACEITECONTRATOREQSERVICE_QNAME, features);
    }

    public SIUserAceiteContratoReqService(URL wsdlLocation) {
        super(wsdlLocation, SIUSERACEITECONTRATOREQSERVICE_QNAME);
    }

    public SIUserAceiteContratoReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIUSERACEITECONTRATOREQSERVICE_QNAME, features);
    }

    public SIUserAceiteContratoReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIUserAceiteContratoReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIUserAceiteContratoReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIUserAceiteContratoReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTP_Port"), SIUserAceiteContratoReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIUserAceiteContratoReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIUserAceiteContratoReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTP_Port"), SIUserAceiteContratoReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIUserAceiteContratoReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIUserAceiteContratoReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTPS_Port"), SIUserAceiteContratoReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIUserAceiteContratoReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIUserAceiteContratoReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTPS_Port"), SIUserAceiteContratoReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIUSERACEITECONTRATOREQSERVICE_EXCEPTION!= null) {
            throw SIUSERACEITECONTRATOREQSERVICE_EXCEPTION;
        }
        return SIUSERACEITECONTRATOREQSERVICE_WSDL_LOCATION;
    }

}
