
package br.com.aevee.port_finan.usuario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_USER_MAINT_req", targetNamespace = "http://www.aevee.com.br/port_finan/usuario")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.usuario.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SIUSERMAINTReq {


    /**
     * 
     * @param mtUSERMAINTReq
     * @return
     *     returns br.com.aevee.port_finan.usuario.DTUSERMAINTResp
     */
    @WebMethod(operationName = "SI_USER_MAINT_req", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_USER_MAINT_resp", targetNamespace = "", partName = "MT_USER_MAINT_resp")
    public DTUSERMAINTResp siUSERMAINTReq(
        @WebParam(name = "MT_USER_MAINT_req", targetNamespace = "", partName = "MT_USER_MAINT_req")
        DTUSERMAINTReq mtUSERMAINTReq);

}
