
package br.com.aevee.port_finan.usuario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_USER_MAINT_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/usuario", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/Portal_Financeiro_Portal_SI_USER_MAINT_resp.wsdl")
public class SIUSERMAINTReqService
    extends Service
{

    private final static URL SIUSERMAINTREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIUSERMAINTREQSERVICE_EXCEPTION;
    private final static QName SIUSERMAINTREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/usuario", "SI_USER_MAINT_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/Portal_Financeiro_Portal_SI_USER_MAINT_resp.wsdl");
            url = new URL(Common.getCorrectWSDLPath("Portal_Financeiro_Portal_SI_USER_MAINT_resp.wsdl "));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIUSERMAINTREQSERVICE_WSDL_LOCATION = url;
        SIUSERMAINTREQSERVICE_EXCEPTION = e;
    }

    public SIUSERMAINTReqService() {
        super(__getWsdlLocation(), SIUSERMAINTREQSERVICE_QNAME);
    }

    public SIUSERMAINTReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIUSERMAINTREQSERVICE_QNAME, features);
    }

    public SIUSERMAINTReqService(URL wsdlLocation) {
        super(wsdlLocation, SIUSERMAINTREQSERVICE_QNAME);
    }

    public SIUSERMAINTReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIUSERMAINTREQSERVICE_QNAME, features);
    }

    public SIUSERMAINTReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIUSERMAINTReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIUSERMAINTReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIUSERMAINTReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTP_Port"), SIUSERMAINTReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIUSERMAINTReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIUSERMAINTReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTP_Port"), SIUSERMAINTReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIUSERMAINTReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIUSERMAINTReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTPS_Port"), SIUSERMAINTReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIUSERMAINTReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIUSERMAINTReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/usuario", "HTTPS_Port"), SIUSERMAINTReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIUSERMAINTREQSERVICE_EXCEPTION!= null) {
            throw SIUSERMAINTREQSERVICE_EXCEPTION;
        }
        return SIUSERMAINTREQSERVICE_WSDL_LOCATION;
    }

}
