
package br.com.aevee.port_finan.log_in;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_LOGIN_req", targetNamespace = "http://www.aevee.com.br/port_finan/log_in")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.log_in.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SILOGINReq {


    /**
     * 
     * @param mtLOGINReq
     * @return
     *     returns br.com.aevee.port_finan.log_in.DTLOGINResp
     */
    @WebMethod(operationName = "SI_LOGIN_req", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_LOGIN_resp", targetNamespace = "", partName = "MT_LOGIN_resp")
    public DTLOGINResp siLOGINReq(
        @WebParam(name = "MT_LOGIN_req", targetNamespace = "", partName = "MT_LOGIN_req")
        DTLOGINReq mtLOGINReq);

}
