
package br.com.aevee.port_finan.log_in;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_LOGIN_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/log_in", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/login.wsdl")
public class SILOGINReqService
    extends Service
{

    private final static URL SILOGINREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SILOGINREQSERVICE_EXCEPTION;
    private final static QName SILOGINREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/log_in", "SI_LOGIN_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/login.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("login.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SILOGINREQSERVICE_WSDL_LOCATION = url;
        SILOGINREQSERVICE_EXCEPTION = e;
    }

    public SILOGINReqService() {
        super(__getWsdlLocation(), SILOGINREQSERVICE_QNAME);
    }

    public SILOGINReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SILOGINREQSERVICE_QNAME, features);
    }

    public SILOGINReqService(URL wsdlLocation) {
        super(wsdlLocation, SILOGINREQSERVICE_QNAME);
    }

    public SILOGINReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SILOGINREQSERVICE_QNAME, features);
    }

    public SILOGINReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SILOGINReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SILOGINReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SILOGINReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/log_in", "HTTP_Port"), SILOGINReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SILOGINReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SILOGINReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/log_in", "HTTP_Port"), SILOGINReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SILOGINReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SILOGINReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/log_in", "HTTPS_Port"), SILOGINReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SILOGINReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SILOGINReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/log_in", "HTTPS_Port"), SILOGINReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SILOGINREQSERVICE_EXCEPTION!= null) {
            throw SILOGINREQSERVICE_EXCEPTION;
        }
        return SILOGINREQSERVICE_WSDL_LOCATION;
    }

}
