
package br.com.aevee.port_finan.log_in;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import br.com.aevee.port_finan.shared.DTRESPONSE;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_PWD_CHANGE_req", targetNamespace = "http://www.aevee.com.br/port_finan/log_in")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.log_in.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SIPWDCHANGEReq {


    /**
     * 
     * @param mtPWDCHANGEReq
     * @return
     *     returns br.com.aevee.port_finan.shared.DTRESPONSE
     */
    @WebMethod(operationName = "PWD_CHANGE", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_PWD_CHANGE_resp", targetNamespace = "", partName = "MT_PWD_CHANGE_resp")
    public DTRESPONSE pwdCHANGE(
        @WebParam(name = "MT_PWD_CHANGE_req", targetNamespace = "", partName = "MT_PWD_CHANGE_req")
        DTPWDCHANGEReq mtPWDCHANGEReq);

}
