
package br.com.aevee.port_finan.adiantamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ADIANTAMENTO_req", targetNamespace = "http://www.aevee.com.br/port_finan/adiantamento")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.adiantamento.ObjectFactory.class,
    br.com.aevee.port_finan.publicacao.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SIADIANTAMENTOReq {


    /**
     * 
     * @param mtLISTARReq
     * @return
     *     returns br.com.aevee.port_finan.adiantamento.DTListarOUT
     */
    @WebMethod(operationName = "Listar", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_LISTAR_resp", targetNamespace = "", partName = "MT_LISTAR_resp")
    public DTListarOUT listar(
        @WebParam(name = "MT_LISTAR_req", targetNamespace = "", partName = "MT_LISTAR_req")
        DTListarINB mtLISTARReq);

    /**
     * 
     * @param mtSolicitacaoReq
     * @return
     *     returns br.com.aevee.port_finan.adiantamento.DTSolicitacaoOUT
     */
    @WebMethod(operationName = "Solicitacao", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Solicitacao_resp", targetNamespace = "", partName = "MT_Solicitacao_resp")
    public DTSolicitacaoOUT solicitacao(
        @WebParam(name = "MT_Solicitacao_req", targetNamespace = "", partName = "MT_Solicitacao_req")
        DTSolicitacaoINB mtSolicitacaoReq);

    /**
     * 
     * @param mtRecalculoReq
     * @return
     *     returns br.com.aevee.port_finan.adiantamento.DTRecalculoOUT
     */
    @WebMethod(operationName = "Recalcular", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Recalculo_resp", targetNamespace = "", partName = "MT_Recalculo_resp")
    public DTRecalculoOUT recalcular(
        @WebParam(name = "MT_Recalculo_req", targetNamespace = "", partName = "MT_Recalculo_req")
        DTSolicitacaoINB mtRecalculoReq);

    /**
     * 
     * @param mtAcompanhamentoReq
     * @return
     *     returns br.com.aevee.port_finan.adiantamento.DTAcompanhamentoOUT
     */
    @WebMethod(operationName = "Acompanhamento", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Acompanhamento_resp", targetNamespace = "", partName = "MT_Acompanhamento_resp")
    public DTAcompanhamentoOUT acompanhamento(
        @WebParam(name = "MT_Acompanhamento_req", targetNamespace = "", partName = "MT_Acompanhamento_req")
        DTAcompanhamentoINB mtAcompanhamentoReq);

}
