
package br.com.aevee.port_finan.adiantamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ADIANTAMENTO_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/adiantamento", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/adiantamento.wsdl")
public class SIADIANTAMENTOReqService
    extends Service
{

    private final static URL SIADIANTAMENTOREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIADIANTAMENTOREQSERVICE_EXCEPTION;
    private final static QName SIADIANTAMENTOREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/adiantamento", "SI_ADIANTAMENTO_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/adiantamento.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("adiantamento.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIADIANTAMENTOREQSERVICE_WSDL_LOCATION = url;
        SIADIANTAMENTOREQSERVICE_EXCEPTION = e;
    }

    public SIADIANTAMENTOReqService() {
        super(__getWsdlLocation(), SIADIANTAMENTOREQSERVICE_QNAME);
    }

    public SIADIANTAMENTOReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIADIANTAMENTOREQSERVICE_QNAME, features);
    }

    public SIADIANTAMENTOReqService(URL wsdlLocation) {
        super(wsdlLocation, SIADIANTAMENTOREQSERVICE_QNAME);
    }

    public SIADIANTAMENTOReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIADIANTAMENTOREQSERVICE_QNAME, features);
    }

    public SIADIANTAMENTOReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIADIANTAMENTOReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIADIANTAMENTOReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIADIANTAMENTOReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/adiantamento", "HTTP_Port"), SIADIANTAMENTOReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIADIANTAMENTOReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIADIANTAMENTOReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/adiantamento", "HTTP_Port"), SIADIANTAMENTOReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIADIANTAMENTOReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIADIANTAMENTOReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/adiantamento", "HTTPS_Port"), SIADIANTAMENTOReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIADIANTAMENTOReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIADIANTAMENTOReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/adiantamento", "HTTPS_Port"), SIADIANTAMENTOReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIADIANTAMENTOREQSERVICE_EXCEPTION!= null) {
            throw SIADIANTAMENTOREQSERVICE_EXCEPTION;
        }
        return SIADIANTAMENTOREQSERVICE_WSDL_LOCATION;
    }

}
