
package br.com.aevee.port_finan.aviso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_Avisos_req", targetNamespace = "http://www.aevee.com.br/port_finan/aviso")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.aviso.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SIAvisosReq {


    /**
     * 
     * @param mtListarAvisosReq
     * @return
     *     returns br.com.aevee.port_finan.aviso.DTListarAvisosResp
     */
    @WebMethod(operationName = "Listar", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Listar_Avisos_resp", targetNamespace = "", partName = "MT_Listar_Avisos_resp")
    public DTListarAvisosResp listar(
        @WebParam(name = "MT_Listar_Avisos_req", targetNamespace = "", partName = "MT_Listar_Avisos_req")
        DTListarAvisosReq mtListarAvisosReq);

    /**
     * 
     * @param mtEsconderMensagemReq
     * @return
     *     returns br.com.aevee.port_finan.aviso.DTEsconderMensagemResp
     */
    @WebMethod(operationName = "EsconderMensagem", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Esconder_Mensagem_resp", targetNamespace = "", partName = "MT_Esconder_Mensagem_resp")
    public DTEsconderMensagemResp esconderMensagem(
        @WebParam(name = "MT_Esconder_Mensagem_req", targetNamespace = "", partName = "MT_Esconder_Mensagem_req")
        DTMensagemLida mtEsconderMensagemReq);

    /**
     * 
     * @param mtMensagemLidaReq
     * @return
     *     returns br.com.aevee.port_finan.aviso.DTEsconderMensagemResp
     */
    @WebMethod(operationName = "MensagemLida", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Mensagem_Lida_resp", targetNamespace = "", partName = "MT_Mensagem_Lida_resp")
    public DTEsconderMensagemResp mensagemLida(
        @WebParam(name = "MT_Mensagem_Lida_req", targetNamespace = "", partName = "MT_Mensagem_Lida_req")
        DTMensagemLida mtMensagemLidaReq);

}
