
package br.com.aevee.port_finan.aviso;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Avisos_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/aviso", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/avisos.wsdl")
public class SIAvisosReqService
    extends Service
{

    private final static URL SIAVISOSREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIAVISOSREQSERVICE_EXCEPTION;
    private final static QName SIAVISOSREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/aviso", "SI_Avisos_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/avisos.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("avisos.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIAVISOSREQSERVICE_WSDL_LOCATION = url;
        SIAVISOSREQSERVICE_EXCEPTION = e;
    }

    public SIAvisosReqService() {
        super(__getWsdlLocation(), SIAVISOSREQSERVICE_QNAME);
    }

    public SIAvisosReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIAVISOSREQSERVICE_QNAME, features);
    }

    public SIAvisosReqService(URL wsdlLocation) {
        super(wsdlLocation, SIAVISOSREQSERVICE_QNAME);
    }

    public SIAvisosReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIAVISOSREQSERVICE_QNAME, features);
    }

    public SIAvisosReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIAvisosReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIAvisosReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIAvisosReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/aviso", "HTTP_Port"), SIAvisosReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIAvisosReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIAvisosReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/aviso", "HTTP_Port"), SIAvisosReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIAvisosReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIAvisosReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/aviso", "HTTPS_Port"), SIAvisosReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIAvisosReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIAvisosReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/aviso", "HTTPS_Port"), SIAvisosReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIAVISOSREQSERVICE_EXCEPTION!= null) {
            throw SIAVISOSREQSERVICE_EXCEPTION;
        }
        return SIAVISOSREQSERVICE_WSDL_LOCATION;
    }

}
