
package br.com.aevee.port_finan.search_help;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_SHLP_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/search_help", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/Portal_Financeiro_Portal_SI_SHLP_resp.wsdl")
public class SISHLPReqService
    extends Service
{

    private final static URL SISHLPREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SISHLPREQSERVICE_EXCEPTION;
    private final static QName SISHLPREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/search_help", "SI_SHLP_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/Portal_Financeiro_Portal_SI_SHLP_resp.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("Portal_Financeiro_Portal_SI_SHLP_resp.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISHLPREQSERVICE_WSDL_LOCATION = url;
        SISHLPREQSERVICE_EXCEPTION = e;
    }

    public SISHLPReqService() {
        super(__getWsdlLocation(), SISHLPREQSERVICE_QNAME);
    }

    public SISHLPReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISHLPREQSERVICE_QNAME, features);
    }

    public SISHLPReqService(URL wsdlLocation) {
        super(wsdlLocation, SISHLPREQSERVICE_QNAME);
    }

    public SISHLPReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISHLPREQSERVICE_QNAME, features);
    }

    public SISHLPReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SISHLPReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SISHLPReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISHLPReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/search_help", "HTTP_Port"), SISHLPReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISHLPReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISHLPReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/search_help", "HTTP_Port"), SISHLPReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SISHLPReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISHLPReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/search_help", "HTTPS_Port"), SISHLPReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISHLPReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISHLPReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/search_help", "HTTPS_Port"), SISHLPReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISHLPREQSERVICE_EXCEPTION!= null) {
            throw SISHLPREQSERVICE_EXCEPTION;
        }
        return SISHLPREQSERVICE_WSDL_LOCATION;
    }

}
