
package br.com.aevee.port_finan.search_help;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_SHLP_req", targetNamespace = "http://www.aevee.com.br/port_finan/search_help")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.search_help.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SISHLPReq {


    /**
     * 
     * @param mtSEARCHHELPReq
     * @return
     *     returns br.com.aevee.port_finan.search_help.DTSHLPResp
     */
    @WebMethod(operationName = "SI_SHLP_req", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SEARCH_HELP_resp", targetNamespace = "", partName = "MT_SEARCH_HELP_resp")
    public DTSHLPResp siSHLPReq(
        @WebParam(name = "MT_SEARCH_HELP_req", targetNamespace = "", partName = "MT_SEARCH_HELP_req")
        DTSHLPReq mtSEARCHHELPReq);

}
