
package br.com.aevee.port_finan.contato;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_Contato_req", targetNamespace = "http://www.aevee.com.br/port_finan/contato")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.contato.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SIContatoReq {


    /**
     * 
     * @param mtContatoEnvioReq
     * @return
     *     returns br.com.aevee.port_finan.contato.DTContatoEnvioResp
     */
    @WebMethod(operationName = "Enviar", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Contato_Envio_resp", targetNamespace = "", partName = "MT_Contato_Envio_resp")
    public DTContatoEnvioResp enviar(
        @WebParam(name = "MT_Contato_Envio_req", targetNamespace = "", partName = "MT_Contato_Envio_req")
        DTContatoEnvioReq mtContatoEnvioReq);

    /**
     * 
     * @param mtContatoReq
     * @return
     *     returns br.com.aevee.port_finan.contato.DTContatoResp
     */
    @WebMethod(operationName = "Inicio", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Contato_resp", targetNamespace = "", partName = "MT_Contato_resp")
    public DTContatoResp inicio(
        @WebParam(name = "MT_Contato_req", targetNamespace = "", partName = "MT_Contato_req")
        DTContatoReq mtContatoReq);

}
