
package br.com.aevee.port_finan.contato;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Contato_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/contato", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/contato.wsdl")
public class SIContatoReqService
    extends Service
{

    private final static URL SICONTATOREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SICONTATOREQSERVICE_EXCEPTION;
    private final static QName SICONTATOREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/contato", "SI_Contato_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/contato.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("contato.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SICONTATOREQSERVICE_WSDL_LOCATION = url;
        SICONTATOREQSERVICE_EXCEPTION = e;
    }

    public SIContatoReqService() {
        super(__getWsdlLocation(), SICONTATOREQSERVICE_QNAME);
    }

    public SIContatoReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SICONTATOREQSERVICE_QNAME, features);
    }

    public SIContatoReqService(URL wsdlLocation) {
        super(wsdlLocation, SICONTATOREQSERVICE_QNAME);
    }

    public SIContatoReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SICONTATOREQSERVICE_QNAME, features);
    }

    public SIContatoReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIContatoReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIContatoReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIContatoReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/contato", "HTTP_Port"), SIContatoReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIContatoReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIContatoReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/contato", "HTTP_Port"), SIContatoReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIContatoReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIContatoReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/contato", "HTTPS_Port"), SIContatoReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIContatoReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIContatoReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/contato", "HTTPS_Port"), SIContatoReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SICONTATOREQSERVICE_EXCEPTION!= null) {
            throw SICONTATOREQSERVICE_EXCEPTION;
        }
        return SICONTATOREQSERVICE_WSDL_LOCATION;
    }

}
