
package br.com.aevee.port_finan.publicacao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Download_PDF_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/publicacao", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/download_PDF.wsdl")
public class SIDownloadPDFReqService
    extends Service
{

    private final static URL SIDOWNLOADPDFREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIDOWNLOADPDFREQSERVICE_EXCEPTION;
    private final static QName SIDOWNLOADPDFREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/publicacao", "SI_Download_PDF_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/download_PDF.wsdl");
        	url = new URL(Common.getCorrectWSDLPath("download_PDF.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIDOWNLOADPDFREQSERVICE_WSDL_LOCATION = url;
        SIDOWNLOADPDFREQSERVICE_EXCEPTION = e;
    }

    public SIDownloadPDFReqService() {
        super(__getWsdlLocation(), SIDOWNLOADPDFREQSERVICE_QNAME);
    }

    public SIDownloadPDFReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIDOWNLOADPDFREQSERVICE_QNAME, features);
    }

    public SIDownloadPDFReqService(URL wsdlLocation) {
        super(wsdlLocation, SIDOWNLOADPDFREQSERVICE_QNAME);
    }

    public SIDownloadPDFReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIDOWNLOADPDFREQSERVICE_QNAME, features);
    }

    public SIDownloadPDFReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIDownloadPDFReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIDownloadPDFReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIDownloadPDFReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTP_Port"), SIDownloadPDFReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIDownloadPDFReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIDownloadPDFReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTP_Port"), SIDownloadPDFReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIDownloadPDFReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIDownloadPDFReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTPS_Port"), SIDownloadPDFReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIDownloadPDFReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIDownloadPDFReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTPS_Port"), SIDownloadPDFReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIDOWNLOADPDFREQSERVICE_EXCEPTION!= null) {
            throw SIDOWNLOADPDFREQSERVICE_EXCEPTION;
        }
        return SIDOWNLOADPDFREQSERVICE_WSDL_LOCATION;
    }

}
