
package br.com.aevee.port_finan.publicacao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_Download_PDF_req", targetNamespace = "http://www.aevee.com.br/port_finan/publicacao")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.aevee.port_finan.publicacao.ObjectFactory.class,
    br.com.aevee.port_finan.shared.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface SIDownloadPDFReq {


    /**
     * 
     * @param mtDownloadPDFReq
     * @return
     *     returns br.com.aevee.port_finan.publicacao.DTDownloadPDFResp
     */
    @WebMethod(operationName = "SI_Download_PDF_req", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Download_PDF_resp", targetNamespace = "", partName = "MT_Download_PDF_resp")
    public DTDownloadPDFResp siDownloadPDFReq(
        @WebParam(name = "MT_Download_PDF_req", targetNamespace = "", partName = "MT_Download_PDF_req")
        DTDownloadPDFReq mtDownloadPDFReq);

}
