
package br.com.aevee.port_finan.publicacao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.aevee.port_finan.Common;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Publicacao_reqService", targetNamespace = "http://www.aevee.com.br/port_finan/publicacao", wsdlLocation = "file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/publicacaoTitulos.wsdl")
public class SIPublicacaoReqService
    extends Service
{

    private final static URL SIPUBLICACAOREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIPUBLICACAOREQSERVICE_EXCEPTION;
    private final static QName SIPUBLICACAOREQSERVICE_QNAME = new QName("http://www.aevee.com.br/port_finan/publicacao", "SI_Publicacao_reqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/eclipse/Convert%20wsdl/Portal%20Financeiro%20-%20Ahmad/publicacaoTitulos.wsdl");
            url = new URL(Common.getCorrectWSDLPath("publicacaoTitulos.wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIPUBLICACAOREQSERVICE_WSDL_LOCATION = url;
        SIPUBLICACAOREQSERVICE_EXCEPTION = e;
    }

    public SIPublicacaoReqService() {
        super(__getWsdlLocation(), SIPUBLICACAOREQSERVICE_QNAME);
    }

    public SIPublicacaoReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIPUBLICACAOREQSERVICE_QNAME, features);
    }

    public SIPublicacaoReqService(URL wsdlLocation) {
        super(wsdlLocation, SIPUBLICACAOREQSERVICE_QNAME);
    }

    public SIPublicacaoReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIPUBLICACAOREQSERVICE_QNAME, features);
    }

    public SIPublicacaoReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIPublicacaoReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIPublicacaoReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPublicacaoReq getHTTPPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTP_Port"), SIPublicacaoReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPublicacaoReq
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPublicacaoReq getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTP_Port"), SIPublicacaoReq.class, features);
    }

    /**
     * 
     * @return
     *     returns SIPublicacaoReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPublicacaoReq getHTTPSPort() {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTPS_Port"), SIPublicacaoReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPublicacaoReq
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPublicacaoReq getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aevee.com.br/port_finan/publicacao", "HTTPS_Port"), SIPublicacaoReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIPUBLICACAOREQSERVICE_EXCEPTION!= null) {
            throw SIPUBLICACAOREQSERVICE_EXCEPTION;
        }
        return SIPUBLICACAOREQSERVICE_WSDL_LOCATION;
    }

}
